config/routes.rb
Journal::Application.routes.draw do
  root :to => "dashboard#index"
  
  devise_for :users, :path => :sessions, :path_names => {:signup => :register}
  #devise_scope :user do
  #  get '/signin' => 'devise/sessions#new', :as => :signin
  #  post '/signin' => 'devise/sessions#create', :as => :authenticate
  #  get '/signup' => 'devise/registrations', :action => 'new', :as => :signup
  #  get '/signout' => 'devise/sessions#destroy'
  #  get '/register' => 'devise/registrations', :action => 'new'
  #end
  resources :specializations
  resources :correspondences
  match '/correspondences/:id/hide' => 'correspondences#hide', :as => :hide
  match '/unhide/:id' => 'correspondences#unhide', :as => :unhide
  match '/hidden_correspondences' => 'correspondences#hidden_correspondences', :as => :hidden_correspondences
  
  resources :submissions do
    resources :assignments, :shallow => true
    resources :associates, :only => [:new, :create]
    #resources :editors, :only => [:new,:create]
    #resources :notifications, :only => [:index,:show] do
    #  post :submit
    #end
    resources :comments, :shallow => true
    resources :states, :shallow => true do
      resources :comments, :shallow => true
    end
    resources :folders, :shallow => true do
      resources :documents, :shallow => true do
        resources :comments, :shallow => true
      end
      resources :comments, :shallow => true
      member do
        post :upload, :as => :upload_documents
        get :download
      end
    end
    member do
      post :revert_state
      get :adopt
    end
    collection do
      get :search
    end
  end
  get '/submissions/:submission_id/notifications' => 'notifications#index', :as => :submission_notifications
  get '/submissions/:submission_id/notifications/:id' => 'notifications#show', :as => :submission_notification
  post '/submissions/:submission_id/notifications/:id/submit' => 'notifications#submit', :as => :submission_notification_submit
  get '/folders/:folder_id/notifications' => 'notifications#index', :as => :folder_notifications
  get '/folders/:folder_id/notifications/:id' => 'notifications#show', :as => :folder_notification
  post '/folders/:folder_id/notifications/:id/submit' => 'notifications#submit', :as => :folder_notification_submit
  resources :users do
    member do
      post :assign_role
    end
  end
  get '/users/:id/roles/:role_id/unassign' => 'users#unassign_role', :as => :unassign_role
  resources :roles
  resources :form_letters do
    resources :tags, :only => [:create,:destroy], :shallow => true
  end
  resources :associates, :only => [:index,:show,:new,:create,:edit,:update]
  resources :editors, :only => [:index,:show,:new,:create,:edit,:update] do
    resources :expertise, :only => [:index,:create,:destroy]
    collection do
      get :search
    end
  end
    
  match '/download_attachment/:id' => 'attachments#download', :as => :download_attachment
  
  get '/activity/:submission' => 'submissions#activity', :as => :activity_on
  get '/activity' => 'submissions#activity'
  #get '/outstanding' => 'submissions#outstanding'
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  include Comparable
  belongs_to :submission
  has_many :documents, :dependent => :destroy
  has_many :comments, :as => :commentable, :dependent => :destroy
  accepts_nested_attributes_for :comments
  has_many :observations, :as => :observable, :dependent => :destroy
  
  has_friendly_id :assignment_id, :use_slug => true
  
  FOLDERS = ['Submission',
             'Review under prescreening',
             'Resubmission under prescreening',
             'Review',
             'Resubmission under review',
             'Resubmission with minor modifications',
             'Review under final screening',
             'Resubmission under final screening',
             'Submission under publication']
             
  FOLDERS.each do |folder|
    #
    # Define array constants
    self.const_set(folder.gsub(/ /, '_').upcase.to_sym, folder)
    #
    # Define scope associations
    scope folder.symbolize, where("activity = '#{folder}'")
  end

  STAGE_1 = [SUBMISSION]
  STAGE_2 = STAGE_1 + [REVIEW_UNDER_PRESCREENING]
  STAGE_3 = STAGE_2 + [RESUBMISSION_UNDER_PRESCREENING]
  STAGE_4 = STAGE_3 + [REVIEW]
  STAGE_5 = STAGE_4 + [RESUBMISSION_UNDER_REVIEW, RESUBMISSION_WITH_MINOR_MODIFICATIONS]
  STAGE_6 = STAGE_5 + [REVIEW_UNDER_FINAL_SCREENING]
  STAGE_7 = STAGE_6 + [RESUBMISSION_UNDER_FINAL_SCREENING]
  STAGE_8 = STAGE_7 + [SUBMISSION_UNDER_PUBLICATION]
  STAGE_9 = STAGE_8
  
  FOLDER_HIERARCHY = Hash[*FOLDERS.zip(1..FOLDERS.length).flatten]
    
  def <=>(other)
    FOLDER_HIERARCHY[self.activity] <=> FOLDER_HIERARCHY[other.activity]
  end
  
  def assignment_id
    submission_slug = ''
    unless self.submission.nil?
      submission_slug = self.submission.cached_slug
    end
    "#{submission_slug}:folder-#{assignment_number}"
  end
  
  def assignment_id=(assign_id)
    assignment_number = "#{assign_id.match(/\d+$/)[0]}"
  end
  
  def normalize_friendly_id(text)
    text
  end
  
  def slug_display
    cached_slug
  end
  
  def activity_attempt_display
    (activity.titleize + (((' ' + attempt.ordinalize) unless attempt < 2) || '')).html_safe
  end
  
  def next_document_assignment
    documents.maximum(:assignment_number).to_i + 1
  end
end

app/controllers/folders_controller.rb
require 'zip/zip'

class FoldersController < ApplicationController
  respond_to :html, :xml
  load_and_authorize_resource
  
  def index
    @submission = Submission.includes(:folders).find(params[:submission_id])
    respond_with @folders = @submission.folders
  end
  
  def show
    @folder = Folder.includes(:submission,:documents,:comments).find(params[:id])
    @submission = @folder.submission
    @documents = @folder.documents
    @comments = @folder.comments
    respond_with @folder
  end
  
  def new
    @submission = Submission.find(params[:submission_id])
    @folder = Folder.new
    respond_with @folder
  end
  
  def create
    @submission = Submission.includes(:folders).find(params[:submission_id])
    @folder = Folder.new(params[:folder])
    @folder.assignment_number = @submission.next_folder_assignment
    @submission.folders << @folder
    @folder.comments << Comment.new(params[:comments]) unless params[:comments][:comment].blank?
    process_multiple_files
    flash[:notice] = 'Folder successfully created!'
    if session[:return_to_state_management]
      session[:return_to_state_management] = false
      respond_with @submission, :location => submission_states_path(@submission)
    else
      respond_with @submission
    end
  end
  
  def edit
    @folder = Folder.includes(:submission, :documents).find(params[:id])
    @submission = @folder.submission
    @documents = @folder.documents
    respond_with @folder
  end
  
  def update
    @folder = Folder.find(params[:id])
    if @folder.update_attributes(params[:folder])
      flash[:notice] = 'Folder successfully updated!'
    end
    respond_with @folder
  end
  
  def destroy
    @folder = Folder.includes(:submission).find(params[:id])
    @submission = @folder.submission
    @folder.destroy
    flash[:notice] = 'Folder successfully destroyed!'
    respond_with @submission
  end
  
  def upload
    @folder = Folder.includes(:submission).find(params[:id])
    @submission = @folder.submission
    process_multiple_files
    respond_with @folder
  end
  
  def download
    @folder = Folder.includes(:documents).find(params[:id])
    file_name = "#{@folder.cached_slug} #{@folder.activity_attempt_display}.zip".gsub(/[: ]/,'_').downcase
    tmp_f = Tempfile.new("#{rand(36**8).to_s(36)}-#{Time.now.strftime("%Y%m%d%H%M%S")}")
    Zip::ZipOutputStream.open(tmp_f.path) do |zip_f|
      @folder.documents.each do |doc|
        zip_f.put_next_entry(doc.working_file.original_filename)
        zip_f.write IO.read(doc.working_file.path)
      end
    end
    send_file(tmp_f.path,
              :filename => file_name,
              :type => 'application/zip',
              :disposition => 'inline')
  end
  
  # Process multiple files passed in through params[:upload_data].
  # Expecting @folder is instantiated
  def process_multiple_files
    params[:upload_data].each do |file|
      document = Document.new(:assignment_number => @folder.next_document_assignment)
      document.working_file = file
      @folder.documents << document
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_documents.html.erb
<%= table_for :documents do %>
  <tr class='header'>
    <td><label>Name</label></td>
    <td>
      <% if current_user.manager? %>
        <label>Actions</label>
      <%- end -%>
    </td>
  </tr>
  <%= render @documents %>
<%- end -%>

app/views/folders/_form.html.erb
<%= upload_form_for(:object => @folder, :action => submission_folders_path(@submission), :place_block => :before) do %>
  <p><label>Activity</label> <%= select_tag "folder[activity]", options_for_select(Folder::FOLDERS), :include_blank => true %> <label>Tag</label> <%= select_tag "folder[tag]", options_for_select(Folder::FOLDER_TAGS), :include_blank => true %></p>
  <p><label>Note</label><br/><%= text_area_tag "folder[note]", nil, :size => "50x8" %></p>
<%- end -%>

app/views/folders/_form_first.html.erb
<%= form_for @folder do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%# f.label :submission_id %><br />
    <%# f.text_field :submission_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/_header.html.erb
<h2 style='margin-bottom: 5px;'><%= link_to_unless_current 'Folder: ' + @folder.activity_attempt_display, folder_path(@folder) %></h2>
<h3 style='margin:0;'>
  <%= @folder.slug_display %>
</h3>

app/views/folders/edit.html.erb
<%= render :partial => 'submissions/breadcrumbs' %>
<%= render :partial => 'submissions/header' %>
<%= render :partial => 'header' %>
<%= form_for @folder do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>
      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p class='field'>
    <%= f.label :activity %><br />
    <%= f.select :activity, @submission.available_folders %>
  </p>
  <p class='field'>
    <%= f.label :attempt %><br />
    <%= f.text_field :attempt, :size => 2, :maxlength => 2 %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/index.html.erb
<h1>Listing folders</h1>
<table>
  <tr>
    <th>Submission</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @folders.each do |folder| %>
  <tr>
    <td><%= folder.submission_id %></td>
    <td><%= link_to 'Show', folder %></td>
    <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
    <td><%= link_to 'Destroy', folder, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%# link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<%- content_for :head do -%>
  <%= javascript_tag do %>
    var next_folder_assignment_numbers = new Array();
    <%- Folder::FOLDERS.each do |value| -%>
    next_folder_assignment_numbers['<%= value %>'] = <%= @submission.folders.send(value.symbolize).count + 1 || '1' %>;
    <%- end -%>
  <% end %>
<%- end -%>
<%= render :partial => 'submissions/breadcrumbs' %>
<%= render :partial => 'submissions/header' %>
<h2>New folder</h2>
<%= render :partial => 'shared/instructions' %>
<%= upload_form_for(:object => @folder, :action => submission_folders_path(@submission), :place_block => :before) do |form| %>
  <p><label>Activity</label> <%= form.select "activity", options_for_select(@submission.available_folders, @submission.default_folder) %></p>
  <p><label>Attempt</label> <%= form.text_field "attempt", :size => 2, :maxlength => 2, :value => @submission.next_assignment_number %></p>
  <%= fields_for :comments do |comment_field| %>
    <p><label>Comment</label><br/><%= comment_field.text_area "comment", :size => "50x8" %></p>
  <% end %>
<%- end -%>

app/views/folders/show.html.erb
<%= render :partial => 'submissions/breadcrumbs' %>
<%= render :partial => 'submissions/header' %>
<%= render :partial => 'header' %>
<p>
  <label>Created:</label>
  <%= @folder.created_at.to_s(:short_display) %>
</p>
<%- if current_user.manager? -%>
<%= link_to 'Edit', edit_folder_path(@folder) %> | 
<%= link_to 'Destroy', @folder, :confirm => 'Are you sure?', :method => :delete %>
<p>
  <label>Notifications:</label>&nbsp;&nbsp;
  <span class='with-min-link'><%= link_to 'Select', folder_notifications_path(@folder), :title => 'Compose and email notifications.' %></span>
</p>
<%- end -%>
<h3>Documents &nbsp;&nbsp;<span class='min-text'><%= link_to 'Download all', download_folder_path(@folder) %></span></h3>
<%= render :partial => 'documents' %>
<%- if current_user.manager? -%>
  <h3>Add documents</h3>
  <%= upload_form_for(:object => @folder, :action => upload_documents_folder_path(@folder)) do |f| %>
  <%- end -%>
<%- end -%>