config/routes.rb
Journal::Application.routes.draw do
  root :to => "dashboard#index"
  
  devise_for :users, :path => :sessions, :path_names => {:signup => :register}
  #devise_scope :user do
  #  get '/signin' => 'devise/sessions#new', :as => :signin
  #  post '/signin' => 'devise/sessions#create', :as => :authenticate
  #  get '/signup' => 'devise/registrations', :action => 'new', :as => :signup
  #  get '/signout' => 'devise/sessions#destroy'
  #  get '/register' => 'devise/registrations', :action => 'new'
  #end
  resources :specializations
  resources :correspondences
  match '/correspondences/:id/hide' => 'correspondences#hide', :as => :hide
  match '/unhide/:id' => 'correspondences#unhide', :as => :unhide
  match '/hidden_correspondences' => 'correspondences#hidden_correspondences', :as => :hidden_correspondences
  
  resources :submissions do
    resources :assignments, :shallow => true
    resources :associates, :only => [:new, :create]
    #resources :editors, :only => [:new,:create]
    #resources :notifications, :only => [:index,:show] do
    #  post :submit
    #end
    resources :comments, :shallow => true
    resources :states, :shallow => true do
      resources :comments, :shallow => true
    end
    resources :folders, :shallow => true do
      resources :documents, :shallow => true do
        resources :comments, :shallow => true
      end
      resources :comments, :shallow => true
      member do
        post :upload, :as => :upload_documents
        get :download
      end
    end
    member do
      post :revert_state
      get :adopt
    end
    collection do
      get :search
    end
  end
  get '/submissions/:submission_id/notifications' => 'notifications#index', :as => :submission_notifications
  get '/submissions/:submission_id/notifications/:id' => 'notifications#show', :as => :submission_notification
  post '/submissions/:submission_id/notifications/:id/submit' => 'notifications#submit', :as => :submission_notification_submit
  get '/folders/:folder_id/notifications' => 'notifications#index', :as => :folder_notifications
  get '/folders/:folder_id/notifications/:id' => 'notifications#show', :as => :folder_notification
  post '/folders/:folder_id/notifications/:id/submit' => 'notifications#submit', :as => :folder_notification_submit
  resources :users do
    member do
      post :assign_role
    end
  end
  get '/users/:id/roles/:role_id/unassign' => 'users#unassign_role', :as => :unassign_role
  resources :roles
  resources :form_letters do
    resources :tags, :only => [:create,:destroy], :shallow => true
  end
  resources :associates, :only => [:index,:show,:new,:create,:edit,:update]
  resources :editors, :only => [:index,:show,:new,:create,:edit,:update] do
    resources :expertise, :only => [:index,:create,:destroy]
    collection do
      get :search
    end
  end
    
  match '/download_attachment/:id' => 'attachments#download', :as => :download_attachment
  
  get '/activity/:submission' => 'submissions#activity', :as => :activity_on
  get '/activity' => 'submissions#activity'
  #get '/outstanding' => 'submissions#outstanding'
end

app/models/correspondence.rb
require 'base64'
class Correspondence < ActiveRecord::Base
  has_many :attachments, :dependent => :destroy
  
  scope :hidden, where("hidden = 'T'")
  scope :unhidden, where("hidden = 'F'")
  scope :without_errors, where("error_status IS NULL")
  scope :with_errors, where("NOT error_status IS NULL")
  scope :with_attachments, includes(:attachments).where('correspondence.id = attachments.correspondence_id')
  
  def body
    Base64::decode64(self[:body])
  end
  
  def body=(value)
    self[:body] = Base64::encode64(value)
  end
  
  def subject
    Base64::decode64(self[:subject])
  end
  
  def subject=(value)
    self[:subject] = Base64::encode64(value)
  end
end

app/controllers/correspondences_controller.rb
class CorrespondencesController < ApplicationController
  respond_to :html, :xml
  load_and_authorize_resource
  before_filter :remember_last_page_visited, :only => [:index, :hidden_correspondences]
  
  def index
    respond_with @correspondences = Correspondence.unhidden.order('created_at DESC').paginate(:page => params[:page], :per_page => 8)
  end

  def show
    @correspondence = Correspondence.includes(:attachments).find(params[:id])
    @attachments = @correspondence.attachments
  end

  def new
    @correspondence = Correspondence.new
  end

  def edit
    
  end

  def create
    @correspondence = Correspondence.new(params[:correspondence])
    if @correspondence.save
      flash[:notice] = "Successfully created correspondence."
    end
    respond_with @correspondence
  end

  def update
  end

  def destroy
  end
  
  def hide
    correspondence = Correspondence.find(params[:id])
    previously_hidden = correspondence.hidden
    correspondence.toggle!(:hidden)
    if previously_hidden
      redirect_to hidden_correspondences_path(:page => session[:last_hidden_correspondences_page])
    else
      redirect_to correspondences_path(:page => session[:last_unhidden_correspondences_page])
    end
  end
  
  def hidden_correspondences
    @correspondences = Correspondence.hidden.order('created_at DESC').paginate(:page => params[:page], :per_page => 8)
    render 'index'
  end
  
  private
  def remember_last_page_visited
    case params[:action]
    when 'index'
      session[:last_unhidden_correspondences_page] = params[:page]
    when 'hidden_correspondences'
      session[:last_hidden_correspondences_page] = params[:page]
    end
  end
end

app/helpers/correspondences_helper.rb
module CorrespondencesHelper
  def toggle_hide_label
    if params[:action] == 'hidden_correspondences'
      'Unhide'
    else
      'Hide'
    end
  end
  
  def back_to_correspondences
    link_to_if(@correspondences.hidden?, 'Submissions', hidden_correspondences_path(:page => session[:last_hidden_correspondences_page])) do
      link_to_unless(@submission.hidden?, 'Submissions', correspondences_path(:page => session[:last_unhidden_correspondences_page]))
    end
  end
  
  def correspondences_navigation
    content_tag :p do
      link_to_unless_current('Unhidden', correspondences_path(:page => session[:last_unhidden_correspondences_page]), :class => 'header-link') +
      " | " +
      link_to_unless_current('Hidden', hidden_correspondences_path(:page => session[:last_hidden_correspondences_page]), :class => 'header-link')
    end
  end
  
  def correspondences_filters
    content_tag :p do
      'Include: ' +
      check_box_tag('hidden') + ' hidden ' +
      check_box_tag('no attachments') + ' without attachments ' +
      check_box_tag('with errors') + ' with errors'
    end
  end
end

app/views/correspondences/_breadcrumbs.html.erb
<span><%= link_to_unless_current 'Home', root_path %></span> > 
<span><%= link_to_unless_current 'Correspondence', correspondences_path %></span>

app/views/correspondences/_correspondence.html.erb
<tr>
  <td><%= link_to correspondence.submission.subject, correspondence_path(correspondence) %></td>
  <td><%= correspondence.submission.display_description %></td>
  <td><%= correspondence.attachments.length %></td>
  <td><%= !correspondence.error_status.nil? %></td>
  <td><%= link_to toggle_hide_label, hide_path(correspondence) %></td>
</tr>

app/views/correspondences/_form.html.erb
<%= form_for @correspondence, correspondences_path do |f| %>
  <% if @correspondence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@correspondence.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @correspondence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from, :value => current_user.name %>
  </div>
  <div class="field">
    <%= f.label :on_behalf_of %><br />
    <%= f.text_field :on_behalf_of, :value => current_user.name %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Create web submission' %>
  </div>
<% end %>

app/views/correspondences/_header.html.erb
<h1><%= link_to_unless_current @correspondence.submission.subject, correspondence_path(@correspondence) %></h1>

app/views/correspondences/_pre_submission_form.html.erb
<p>
  <%= f.label :subject %><br />
  <%= f.text_field :subject %>
</p>
<p>
  <%= f.label :message %><br />
  <%= f.text_area :message %>
</p>

app/views/correspondences/_submission.html.erb
<%- if @correspondence.submission_type == 'EmailPreSubmission'  -%>
<h1><%= @correspondence.submission.subject %></h1>
<p>
  <label>From</label><br/>
  <%= @correspondence.submission.from %>
</p>
<p>
  <label>Submitted</label><br/>
  <%= @correspondence.submission.submitted_at %>
</p>
<p>
  <label>Message</label><br/>
  <div style='height: 20em; overflow: scroll; width: 940px; border: 2px solid #ccc; padding-left: 12px;'><%= simple_format(@correspondence.submission.body) %></div>
</p>
<%- end -%>
<%- if @correspondence.submission_type == 'WebPreSubmission' -%>
<p>
  <label>From</label><br/>
  <%# @correspondence.submission.from %>
</p>
<p>
  <label>Submitted</label><br/>
  <%= @correspondence.submission.created_at %>
</p>
<p>
  <label>Message</label><br/>
  <div style='height: 20em; overflow: scroll; width: 940px; border: 2px solid #ccc; padding-left: 12px;'><%= simple_format(@correspondence.submission.message) %></div>
</p>
<%- end -%>

app/views/correspondences/edit.html.erb
<%= render :partial => 'breadcrumbs' %>
<%= render :partial => 'header' %>
<p>Find me in app/views/correspondences/edit.html.erb</p>

app/views/correspondences/index.html.erb
<%= render :partial => 'dashboard/header' %>
<h1>Correspondences</h1>
<%= correspondences_navigation %>
<%= table_for :entities do %>
  <tr class='header'>
    <td><label>Subject</label></td>
    <td><label>Description</label></td>
    <td><label>Attachments</label></td>
    <td><label>Errors?</label></td>
    <td><label>Actions</label></td>
  </tr>
  <%= render :partial => 'correspondence', :collection => @correspondences %>
<%- end -%>
<br />
<%= will_paginate @correspondences %>
<hr />
<%= link_to 'New correspondence', new_correspondence_path %>

app/views/correspondences/new.html.erb
<%= render :partial => 'breadcrumbs' %>
<h1>New correspondence</h1>
<%= render 'form' %>

app/views/correspondences/show.html.erb
<%= render :partial => 'breadcrumbs' %>
<%= render :partial => 'header' %>

<%= render :partial => 'submission' %>

<%= link_to 'Edit', edit_correspondence_path(@correspondence) %>
<h2>
  <label>Attachments</label>
</h2>
<%= table_for :attachments do %>
  <tr class='header'>
    <td><label>Name</label></td>
  </tr>
  <%= render @attachments %>
<%- end  %>