config/routes.rb
Journal::Application.routes.draw do
  root :to => "dashboard#index"
  
  devise_for :users, :path => :sessions, :path_names => {:signup => :register}
  #devise_scope :user do
  #  get '/signin' => 'devise/sessions#new', :as => :signin
  #  post '/signin' => 'devise/sessions#create', :as => :authenticate
  #  get '/signup' => 'devise/registrations', :action => 'new', :as => :signup
  #  get '/signout' => 'devise/sessions#destroy'
  #  get '/register' => 'devise/registrations', :action => 'new'
  #end
  resources :specializations
  resources :correspondences
  match '/correspondences/:id/hide' => 'correspondences#hide', :as => :hide
  match '/unhide/:id' => 'correspondences#unhide', :as => :unhide
  match '/hidden_correspondences' => 'correspondences#hidden_correspondences', :as => :hidden_correspondences
  
  resources :submissions do
    resources :assignments, :shallow => true
    resources :associates, :only => [:new, :create]
    #resources :editors, :only => [:new,:create]
    #resources :notifications, :only => [:index,:show] do
    #  post :submit
    #end
    resources :comments, :shallow => true
    resources :states, :shallow => true do
      resources :comments, :shallow => true
    end
    resources :folders, :shallow => true do
      resources :documents, :shallow => true do
        resources :comments, :shallow => true
      end
      resources :comments, :shallow => true
      member do
        post :upload, :as => :upload_documents
        get :download
      end
    end
    member do
      post :revert_state
      get :adopt
    end
    collection do
      get :search
    end
  end
  get '/submissions/:submission_id/notifications' => 'notifications#index', :as => :submission_notifications
  get '/submissions/:submission_id/notifications/:id' => 'notifications#show', :as => :submission_notification
  post '/submissions/:submission_id/notifications/:id/submit' => 'notifications#submit', :as => :submission_notification_submit
  get '/folders/:folder_id/notifications' => 'notifications#index', :as => :folder_notifications
  get '/folders/:folder_id/notifications/:id' => 'notifications#show', :as => :folder_notification
  post '/folders/:folder_id/notifications/:id/submit' => 'notifications#submit', :as => :folder_notification_submit
  resources :users do
    member do
      post :assign_role
    end
  end
  get '/users/:id/roles/:role_id/unassign' => 'users#unassign_role', :as => :unassign_role
  resources :roles
  resources :form_letters do
    resources :tags, :only => [:create,:destroy], :shallow => true
  end
  resources :associates, :only => [:index,:show,:new,:create,:edit,:update]
  resources :editors, :only => [:index,:show,:new,:create,:edit,:update] do
    resources :expertise, :only => [:index,:create,:destroy]
    collection do
      get :search
    end
  end
    
  match '/download_attachment/:id' => 'attachments#download', :as => :download_attachment
  
  get '/activity/:submission' => 'submissions#activity', :as => :activity_on
  get '/activity' => 'submissions#activity'
  #get '/outstanding' => 'submissions#outstanding'
end

app/models/form_letter.rb
class FormLetter < ActiveRecord::Base
  has_many :tags, :as => :taggable, :dependent => :destroy
  has_friendly_id :name, :use_slug => true
  
  NOTIFIABLE_TYPES = ['Submission', 'Folder']
end

app/controllers/form_letters_controller.rb
class FormLettersController < ApplicationController
  respond_to :html, :xml
  load_and_authorize_resource

  def index
    paginate_params = {:page => params[:page], :per_page => 5}
    respond_with @form_letters = FormLetter.order('notifiable_type ASC, name ASC').paginate(paginate_params)
  end

  def show
    @form_letter = FormLetter.includes(:tags).find(params[:id])
    @tags = @form_letter.tags
    @tags_selection = (Submission.state_machine.states.keys.sort.map{|key| key.to_s} - @tags.map{|tag| tag.name})
    respond_with @form_letter
  end

  def new
    @form_letter = FormLetter.new
    populate_form_fields
    respond_with @form_letter
  end

  def edit
    @form_letter = FormLetter.find(params[:id])
    populate_form_fields
    respond_with @form_letter
  end

  def create
    @form_letter = FormLetter.new(params[:form_letter])
    if @form_letter.save
      flash[:notice] = "Successfully created form letter."
    end
    respond_with @form_letter
  end
  
  def update
    @form_letter = FormLetter.find(params[:id])
    if @form_letter.update_attributes(params[:form_letter])
      flash[:notice] = "Successfully updated form letter."
    end
    respond_with @form_letter
  end

  def destroy
    @form_letter = FormLetter.find(params[:id])
    @form_letter.destroy
    flash[:notice] = "Successfully destroyed form letter."
    respond_wth @form_letter
  end
  
  def populate_form_fields
    @from = @form_letter.default_from || Journal::FormLetters::FROM.join(', ')
    @reply_to = @form_letter.default_reply_to || Journal::FormLetters::REPLY_TO.join(', ')
    @cc = @form_letter.default_cc_recipients || Journal::FormLetters::REPLY_TO.join(', ')
    @signature = @form_letter.signature || Journal::FormLetters::SIGNATURE
  end
end

app/helpers/form_letters_helper.rb
module FormLettersHelper
end

app/views/form_letters/_breadcrumbs.html.erb
<span><%= link_to_unless_current 'Home', root_path %></span> > 
<span><%= link_to_unless_current 'Form Letters', form_letters_path %></span>

app/views/form_letters/_form.html.erb
<%= form_for(@form_letter) do |f| %>
  <% if @form_letter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form_letter.errors.count, "error") %> prohibited this form_letter from being saved:</h2>
      <ul>
      <% @form_letter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 80 %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.text_field :default_recipients, :size => 80 %>
  </div>
  <div class="field">
    <%= f.label :cc %><br />
    <%= f.text_field :default_cc_recipients, :size => 80, :value => @cc %>
  </div>
  <div class="field">
    <%= f.label :bcc %><br />
    <%= f.text_field :default_bcc_recipients, :size => 80 %>
  </div>
  <div class="field">
    <%= f.label :reply_to %><br />
    <%= f.text_field :default_reply_to, :size => 80, :value => @reply_to %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject, :size => 80 %>
  </div>
  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :default_from, :size => 80, :value => @from %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :size => '80x20' %>
  </div>
  <div class="field">
    <%= f.label :signature %><br />
    <%= f.text_area :signature, :size => '80x10', :value => @signature %>
  </div>
  <div class="field">
    <%= f.label :notifiable_type %><br />
    <%= f.select :notifiable_type, FormLetter::NOTIFIABLE_TYPES, :value => @form_letter.notifiable_type %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/form_letters/_form_letter.html.erb
<tr>
  <td style='width: 20%;'><%= link_to form_letter.name, form_letter, :title => "#{form_letter.body}" %></td>
  <td><%= truncate(form_letter.body, :length => 240) %></td>
  <td><%= form_letter.notifiable_type %></td>
</tr>

app/views/form_letters/_header.html.erb
<h1 style='margin-bottom: 8px;'><%= link_to_unless_current @form_letter.name, form_letter_path(@form_letter) %></h1>

app/views/form_letters/_tag.html.erb
<tr>
  <td><%= tag.name.titleize %></td>
  <td><%= link_to 'Remove', tag_path(tag), :confirm => 'Are you sure?', :method => :delete %></td>
</tr>

app/views/form_letters/_tags.html.erb
<h2>Tags</h2>
<%= table_for :tags do %>
  <tr class='header'>
    <td><label>Name</label></td>
    <td><label>Actions</label></td>
  </tr>
  <%= render :partial => 'tag', :collection => @tags %>
<% end %>

app/views/form_letters/edit.html.erb
<%= render :partial => 'breadcrumbs' %>
<%= render :partial => 'header' %>
<%= render 'form' %>

app/views/form_letters/index.html.erb
<%= render :partial => 'dashboard/header' %>
<h1>Form letters</h1>

<%= table_for :form_letters do %>
  <tr class='header'>
    <td><label>Name</label></td>
    <td><label>Body</label></td>
    <td><label>Type</label></td>
  </tr>
  <%= render :partial => 'form_letter', :collection => @form_letters %>
<%- end -%>
<br />
<%= will_paginate @form_letters %>
<hr/>
<%= link_to 'New Form letter', new_form_letter_path %>

app/views/form_letters/new.html.erb
<%= render :partial => 'breadcrumbs' %>
<h1>New form letter</h1>
<%= render 'form' %>

app/views/form_letters/show.html.erb
<%= render :partial => 'breadcrumbs' %>
<%= render :partial => 'header' %>
<p>
  <b>To:</b>
  <%= @form_letter.default_recipients %>
</p>
<p>
  <b>Cc:</b>
  <%= @form_letter.default_cc_recipients %>
</p>
<p>
  <b>Bcc:</b>
  <%= @form_letter.default_bcc_recipients %>
</p>
<p>
  <b>Reply to:</b>
  <%= @form_letter.default_reply_to %>
</p>
<p>
  <b>Subject:</b>
  <%= @form_letter.subject %>
</p>
<p>
  <b>From:</b>
  <%= @form_letter.default_from %>
</p>
<p class='with-min-link'>
  <b>Body:</b>&nbsp;&nbsp;&nbsp;<%= link_to 'Show', '#', :id => 'form_letter_body_control' %>
  <div style='display:none;' id='form_letter_body'><%= simple_format(@form_letter.body) %></div>
</p>
<p>
  <b>Signature:</b>
  <%= simple_format(@form_letter.signature) %>
</p>
<p>
  <b>Notifiable type:</b>
  <%= @form_letter.notifiable_type %>
</p>
<%= link_to 'Edit', edit_form_letter_path(@form_letter) %> |
<%= link_to 'Destroy', @form_letter, :confirm => 'Are you sure?', :method => :delete, :title => 'Destroy this submission.' %>
<%= render 'tags' %>
<h3>Assign tag</h3>
<%= form_tag form_letter_tags_path(@form_letter) do %>
  <%= select_tag 'name', options_for_select(@tags_selection.map{|tag| [tag.titleize, tag]}) %>
  <%= submit_tag 'Add' %>
<% end %>