config/routes.rb
Journal::Application.routes.draw do
  root :to => "dashboard#index"
  
  devise_for :users, :path => :sessions, :path_names => {:signup => :register}
  #devise_scope :user do
  #  get '/signin' => 'devise/sessions#new', :as => :signin
  #  post '/signin' => 'devise/sessions#create', :as => :authenticate
  #  get '/signup' => 'devise/registrations', :action => 'new', :as => :signup
  #  get '/signout' => 'devise/sessions#destroy'
  #  get '/register' => 'devise/registrations', :action => 'new'
  #end
  resources :specializations
  resources :correspondences
  match '/correspondences/:id/hide' => 'correspondences#hide', :as => :hide
  match '/unhide/:id' => 'correspondences#unhide', :as => :unhide
  match '/hidden_correspondences' => 'correspondences#hidden_correspondences', :as => :hidden_correspondences
  
  resources :submissions do
    resources :assignments, :shallow => true
    resources :associates, :only => [:new, :create]
    #resources :editors, :only => [:new,:create]
    #resources :notifications, :only => [:index,:show] do
    #  post :submit
    #end
    resources :comments, :shallow => true
    resources :states, :shallow => true do
      resources :comments, :shallow => true
    end
    resources :folders, :shallow => true do
      resources :documents, :shallow => true do
        resources :comments, :shallow => true
      end
      resources :comments, :shallow => true
      member do
        post :upload, :as => :upload_documents
        get :download
      end
    end
    member do
      post :revert_state
      get :adopt
    end
    collection do
      get :search
    end
  end
  get '/submissions/:submission_id/notifications' => 'notifications#index', :as => :submission_notifications
  get '/submissions/:submission_id/notifications/:id' => 'notifications#show', :as => :submission_notification
  post '/submissions/:submission_id/notifications/:id/submit' => 'notifications#submit', :as => :submission_notification_submit
  get '/folders/:folder_id/notifications' => 'notifications#index', :as => :folder_notifications
  get '/folders/:folder_id/notifications/:id' => 'notifications#show', :as => :folder_notification
  post '/folders/:folder_id/notifications/:id/submit' => 'notifications#submit', :as => :folder_notification_submit
  resources :users do
    member do
      post :assign_role
    end
  end
  get '/users/:id/roles/:role_id/unassign' => 'users#unassign_role', :as => :unassign_role
  resources :roles
  resources :form_letters do
    resources :tags, :only => [:create,:destroy], :shallow => true
  end
  resources :associates, :only => [:index,:show,:new,:create,:edit,:update]
  resources :editors, :only => [:index,:show,:new,:create,:edit,:update] do
    resources :expertise, :only => [:index,:create,:destroy]
    collection do
      get :search
    end
  end
    
  match '/download_attachment/:id' => 'attachments#download', :as => :download_attachment
  
  get '/activity/:submission' => 'submissions#activity', :as => :activity_on
  get '/activity' => 'submissions#activity'
  #get '/outstanding' => 'submissions#outstanding'
end

app/controllers/expertise_controller.rb
class ExpertiseController < ApplicationController
  respond_to :html, :xml
  load_and_authorize_resource :user #:class => 'User'
  
  def index
    @associate = User.includes(:specializations).find(params[:editor_id])
    if allowed?
      @specializations = @associate.specializations.order('specializations.category, specializations.name')
      @available_specializations = {}
      Specialization.order('category,name').all.group_by(&:category).each_pair{|key,val| @available_specializations[key] = val.collect{|s| s.name unless @specializations.include?(s)}.reject {|s| s.blank?}}
    else
      redirect_to_personal_expertise_page
    end
  end
  
  def create
    @associate = User.includes(:specializations).find(params[:editor_id])
    if allowed?
      flash[:notice] = 'Expertise successfully added.'
      specialization = Specialization.find_by_name(params[:specialization][:name])
      @associate.specializations << specialization unless @associate.specializations.include? specialization
      respond_with @associate, :location => editor_expertise_index_path(@associate)
    else
      redirect_to_personal_expertise_page
    end
  end
  
  def destroy
    @associate = User.includes(:specializations).find(params[:editor_id])
    if allowed?
      flash[:notice] = 'Expertise successfully removed.'
      @associate.specializations.delete(Specialization.find(params[:id]))
      respond_with @associate, :location => editor_expertise_index_path(@associate)
    else
      redirect_to_personal_expertise_page
    end
  end
  
  def allowed?
    current_user.manager? || (current_user == @associate)
  end
  
  def redirect_to_personal_expertise_page
    flash[:notice] = "Editing access restricted to this list only!"
    redirect_to editor_expertise_index_path(current_user)
  end
end

app/helpers/expertise_helper.rb
module ExpertiseHelper
end

app/views/expertise/_breadcrumbs.html.erb
<span><%= link_to_unless_current 'Home', root_path %></span> > 
<span><%= link_to_unless_current 'Editorial Board', editors_path(:page => session[:last_editors_page]) %></span>

app/views/expertise/_header.html.erb
<h1><%= link_to_unless_current @associate.name, editor_path(@associate) %></h1>

app/views/expertise/_specialization.html.erb
<tr>
  <td><%= specialization.name %></td>
  <td><%= specialization.category %></td>
  <td><%= link_to 'Unassign', editor_expertise_path(@associate,specialization), :method => :delete %></td>
</tr>

app/views/expertise/index.html.erb
<%= render :partial => 'breadcrumbs' %>
<%= render :partial => 'header' %>
<h2>Expertise management</h2>
<h3>Expertise</h3>
<%= table_for :specializations do %>
  <tr class='header'>
    <td><label>Name</label></td>
    <td><label>Catagory</label></td>
    <td><label>Actions</label></td>
  </tr>
  <%= render :partial => 'specialization', :collection => @specializations %>
<%- end -%>
<h3>Assign</h3>
<%= form_for @associate, :url => editor_expertise_index_path(@associate), :html => {:method => :post}  do |associate| %>
  <%= fields_for :specialization do |specialization_form| %>
    <%= specialization_form.select :name, grouped_options_for_select(@available_specializations) %>
  <% end %>
  <%= associate.submit 'Assign' %>
<% end %>